model:
  model_path: "togethercomputer/GPT-JT-6B-v1"  # Name of hf model to load
  tokenizer_path: "togethercomputer/GPT-JT-6B-v1"  # Name of hf tokenizer to load
  model_type: "AcceleratePPOModel"  # Name of accelerate model type to load
  num_layers_unfrozen: 2  # Number of bottom layers to freeze during training

train:
  seq_length: 1500  # Size of LM context
  epochs: 4  # Train for max(epochs, total_steps)
  total_steps: 99999999999  # Train for max(epochs, total_steps)
  batch_size: 4  # batch size

  lr_init: 1e-5  # init learning rate
  lr_target: 1e-5  # target final learning rate
  opt_betas: [0.9, 0.95] # adam betas
  opt_eps: 1.0e-8  # adam eps
  weight_decay: 1.0e-6  # weight decay param

  checkpoint_interval: 10000  # checkpoint interval
  eval_interval: 99999999999999 # eval interval, never please

  pipeline: "PPOPipeline"  # prompt pipeline to load
  orchestrator: "PPOOrchestrator"  # orchestrator to load

method:
  name: 'ppoconfig'  # Name of RL method config
  num_rollouts: 128  # Number of rollouts to collect per epoch
  chunk_size: 128  # Number of rollouts to collect in one loop of orchestrator
  ppo_epochs: 1  # Number of ppo epochs
  init_kl_coef: 2  # init kl coefficient
  target: null  # target kl coefficient, set None for fixed kl coef
  horizon: 10000  # PPO horizon
  gamma: 1  # PPO discount
  lam: 0.95  # PPO lambda
  cliprange: 0.01  # clip range
  cliprange_value: 0.01  # clip range
  vf_coef: 2.3  # value term weight
  scale_reward: False # False | "ref" | "running" estimate against which to scale rewards
  ref_mean: null
  ref_std: null # rescale rewards with this deviation
  cliprange_reward: 10
  gen_kwargs:
    min_length: 10
